const RoutesTutorApp = [
/**** Start - Tutor App ****/
  {
    path: '/tutor-app/',
    redirect: '/tutor-app/dashboard',
  },
  {
    path: '/tutor-app/dashboard',
    name: 'Dashboard',
    icon: 'Dashboard',
    access: 'isTutor',
    layout: 'mix',
    component: './tutor-app/dashboard',
  },
  {
    path: '/tutor-app/profile',
    name: 'Profile',
    hideInMenu: true,
    layout: 'mix',
    component: './tutor-app/current-user/profile',
  },
  {
    path: '/tutor-app/students',
    name: 'Students',
    icon: 'TeamOutlined',
    access: 'isTutor',
    layout: 'mix',
    component: './tutor-app/students/list-students',
  },
  {
    path: '/tutor-app/classes',
    name: 'Classes',
    icon: 'SolutionOutlined',
    access: 'isTutor',
    layout: 'mix',
    component: './tutor-app/classes/list-classes',
  },
  {
    path: '/tutor-app/classes/new',
    hideInMenu: true,
    name: 'Create Class',
    access: 'isTutor',
    layout: 'mix',
    component: './tutor-app/classes/create-class',
  },
  {
    path: '/tutor-app/classes/edit/:id',
    hideInMenu: true,
    name: 'Edit Class',
    access: 'isTutor',
    layout: 'mix',
    component: './tutor-app/classes/update-class',
  },
  {
    path: '/tutor-app/quizzes',
    name: 'Quizzes',
    icon: 'FieldTimeOutlined',
    access: 'isTutor',
    layout: 'mix',
    component: './tutor-app/quizzes/list-quizzes',
  },
  {
    path: '/tutor-app/quizzes/new',
    hideInMenu: true,
    name: 'Create Quiz',
    access: 'isTutor',
    layout: 'mix',
    component: './tutor-app/quizzes/create-quiz',
  },
  {
    path: '/tutor-app/quizzes/edit/:id',
    hideInMenu: true,
    name: 'Edit Quiz',
    access: 'isTutor',
    layout: 'mix',
    component: './tutor-app/quizzes/update-quiz',
  },
/**** End - Tutor App ****/
];
export default RoutesTutorApp;